from advancedlinkedlist import *

a = linkedlist()
print(a)
a.add('hi')
print(a)
a.add('hello')
print(a)
a.add('goodbye')
print(a)
print('========')
b = linkedlist('a', 'b', 'c', 'd')
print(b)
b.add('asdf')
print(b)
b.add('adsfasdfadsfadsfadfs')
print(b)